### ISSUE TITLE
Crashes immediately

### ISSUE THREAD

**Issue by sonofevil** [vawser/MapBuddy#1]
The app crashes immediately, silently on launch.

Crash logs:
```
Application: MapBuddy.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Xylozi\Documents\C# Projects\MapBuddy\MapBuddy\bin\Debug\net7.0-windows\example_mod\map\mapstudio'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFileSystemEntries(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at MapBuddy.MainWindow.UpdateMapSelection(String path) in C:\Users\Xylozi\Documents\C# Projects\MapBuddy\MapBuddy\MainWindow.cs:line 56
   at MapBuddy.MainWindow..ctor() in C:\Users\Xylozi\Documents\C# Projects\MapBuddy\MapBuddy\MainWindow.cs:line 52
   at MapBuddy.Program.Main() in C:\Users\Xylozi\Documents\C# Projects\MapBuddy\MapBuddy\Program.cs:line 14

```
```
Faulting application name: MapBuddy.exe, version: 1.0.0.0, time stamp: 0x6377ba57
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3393, time stamp: 0x6b4de7c9
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x3a00
Faulting application start time: 0x01d9f0bea49f0aa9
Faulting application path: D:\users\lutra\Downloads\MapBuddy_0_0_2\MapBuddy.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 0612f8a3-6b3e-45e6-8ef9-5976c7684314
Faulting package full name: 
Faulting package-relative application ID: 
```

Does this app require a specific version NET runtime version?

**Comment by sonofevil** [comment]
Wait, is the app trying to access a path in your home folder?
`Could not find a part of the path 'C:\Users\Xylozi\Documents\C# Projects\MapBuddy\MapBuddy\bin\Debug\net7.0-windows\example_mod\map\mapstudio'.`

**Comment by Auram** [comment]
Confirmed this is still the case. Pulling the source code, changing the mod_path manually and rebuilding works perfectly fine. Vawser please fix this!

**Comment by tensesailor** [comment]
> Confirmed this is still the case. Pulling the source code, changing the mod_path manually and rebuilding works perfectly fine. Vawser please fix this!

Would really appreciate a summary of how to do this for myself since I am experiencing the same issue you had
